In [1]:
import pandas as pd

df = pd.read_csv('csv/food_rows.csv')

In [2]:
df.columns

Index(['ID', 'TYPE', 'PROGRAM', 'ORG PHONE', 'DAYS', 'HOURS', 'LONGITUDE',
       'LATITUDE', 'FULL ADDRESS', 'BOROUGH', 'ZICODE', 'WEEKS_OPEN', 'mon',
       'tue', 'wed', 'thur', 'fri', 'sat', 'sun'],
      dtype='object')

In [3]:
df['WEEKS_OPEN'].value_counts()

WEEKS_OPEN
2,4                29
1,3                26
1,2,3,4             9
2ND                 6
3RD                 5
4TH                 3
3                   3
4                   3
1                   3
2                   2
1ST                 2
2,3,4               2
4,2                 2
1,2,3               2
3,1                 2
CLOSED 5TH WED      1
1st                 1
,4                  1
4TH ONLY            1
1,2,4,5,3           1
1,3,2,4             1
1ST,3RD             1
BY APPT             1
SR ONLY             1
LAST                1
1,2,3,4,1,2,3,4     1
2,3                 1
1,3,5,2,4           1
1,2,3,4,4           1
2,LAST              1
Name: count, dtype: int64

In [4]:

# Function to standardize the week numbers, handling non-string inputs
def standardize_weeks(weeks_open):
    if isinstance(weeks_open, str):  # Only process if it's a string
        weeks_open = weeks_open.replace('1st', '1').replace('2ND', '2').replace('3RD', '3').replace('4TH', '4')
        weeks_open = weeks_open.replace('LAST', '4').replace('BY APPT', 'APPT').replace('SR ONLY', 'SR')
        weeks_open = weeks_open.replace('CLOSED 5TH WED', 'CLOSED').replace('4TH ONLY', '4')
        return weeks_open
    else:
        return weeks_open  # Return the value as-is if it's not a string

# Apply the standardization function to the WEEKS_OPEN column
df['WEEKS_OPEN_STANDARDIZED'] = df['WEEKS_OPEN'].apply(standardize_weeks)

In [5]:
df['WEEKS_OPEN_STANDARDIZED'].value_counts()

WEEKS_OPEN_STANDARDIZED
2,4                30
1,3                26
1,2,3,4             9
2                   8
3                   8
4                   7
1                   4
2,3,4               2
4,2                 2
3,1                 2
1ST                 2
1,2,3               2
1,2,3,4,4           1
SR                  1
CLOSED              1
2,3                 1
1,3,5,2,4           1
1,2,3,4,1,2,3,4     1
1,3,2,4             1
1ST,3               1
APPT                1
1,2,4,5,3           1
4 ONLY              1
,4                  1
Name: count, dtype: int64

In [6]:
def normalize_weeks(weeks_open):
    if isinstance(weeks_open, str):
        # Split the string into a list, remove duplicates, and sort the list
        weeks = sorted(set(week.strip() for week in weeks_open.split(',') if week.strip() != ''))
        return ','.join(weeks)
    else:
        return weeks_open  # Return the value as-is if it's not a string

df['WEEKS_OPEN_NORMALIZED'] = df['WEEKS_OPEN_STANDARDIZED'].apply(normalize_weeks)

In [7]:
df['WEEKS_OPEN_NORMALIZED'].value_counts()

WEEKS_OPEN_NORMALIZED
2,4          32
1,3          28
1,2,3,4      12
2             8
4             8
3             8
1             4
1ST           2
1,2,3,4,5     2
2,3,4         2
1,2,3         2
CLOSED        1
SR            1
2,3           1
1ST,3         1
APPT          1
4 ONLY        1
Name: count, dtype: int64

In [8]:
def handle_special_cases(weeks_open):
    if isinstance(weeks_open, str):
        # Replace special cases with their appropriate values
        weeks_open = weeks_open.replace('1ST', '1').replace('4 ONLY', '4')
        # Keep special cases as they are
        if weeks_open in ['CLOSED', 'SR', 'APPT']:
            return weeks_open
        else:
            # Normalize the weeks after replacing special cases
            weeks = sorted(set(week.strip() for week in weeks_open.split(',') if week.strip() != ''))
            return ','.join(weeks)
    else:
        return weeks_open  # Return the value as-is if it's not a string

df['WEEKS_OPEN_PROCESSED'] = df['WEEKS_OPEN_NORMALIZED'].apply(handle_special_cases)

In [9]:
df['WEEKS_OPEN_PROCESSED'].value_counts()

WEEKS_OPEN_PROCESSED
2,4          32
1,3          29
1,2,3,4      12
4             9
2             8
3             8
1             6
2,3,4         2
1,2,3         2
1,2,3,4,5     2
APPT          1
CLOSED        1
SR            1
2,3           1
Name: count, dtype: int64

In [10]:
# Drop rows where WEEKS_OPEN_PROCESSED is 'APPT', 'CLOSED', or 'SR'
df = df[~df['WEEKS_OPEN_PROCESSED'].isin(['APPT', 'CLOSED', 'SR'])]

# Display the DataFrame to confirm the rows were dropped
print(df[['WEEKS_OPEN_PROCESSED']].value_counts())

WEEKS_OPEN_PROCESSED
2,4                     32
1,3                     29
1,2,3,4                 12
4                        9
2                        8
3                        8
1                        6
1,2,3                    2
1,2,3,4,5                2
2,3,4                    2
2,3                      1
Name: count, dtype: int64

In [11]:
import numpy as np

# Step 1: Fill empty or NaN values with '1,2,3,4,5' to represent all weeks
df['WEEKS_OPEN_PROCESSED'] = df['WEEKS_OPEN_PROCESSED'].replace('', np.nan).fillna('1,2,3,4,5')

# Step 2: Create boolean columns for each week
df['WEEK_1'] = df['WEEKS_OPEN_PROCESSED'].apply(lambda x: '1' in x)
df['WEEK_2'] = df['WEEKS_OPEN_PROCESSED'].apply(lambda x: '2' in x)
df['WEEK_3'] = df['WEEKS_OPEN_PROCESSED'].apply(lambda x: '3' in x)
df['WEEK_4'] = df['WEEKS_OPEN_PROCESSED'].apply(lambda x: '4' in x)
df['WEEK_5'] = df['WEEKS_OPEN_PROCESSED'].apply(lambda x: '5' in x)

In [12]:
df.dtypes

ID                           int64
TYPE                        object
PROGRAM                     object
ORG PHONE                   object
DAYS                        object
HOURS                       object
LONGITUDE                  float64
LATITUDE                   float64
FULL ADDRESS                object
BOROUGH                     object
ZICODE                       int64
WEEKS_OPEN                  object
mon                           bool
tue                           bool
wed                           bool
thur                          bool
fri                           bool
sat                           bool
sun                           bool
WEEKS_OPEN_STANDARDIZED     object
WEEKS_OPEN_NORMALIZED       object
WEEKS_OPEN_PROCESSED        object
WEEK_1                        bool
WEEK_2                        bool
WEEK_3                        bool
WEEK_4                        bool
WEEK_5                        bool
dtype: object

In [13]:
df.drop(columns=['WEEKS_OPEN_STANDARDIZED', 'WEEKS_OPEN_NORMALIZED', 'WEEKS_OPEN'], inplace=True)

In [14]:
df.rename(columns={'WEEKS_OPEN_PROCESSED': 'WEEKS_OPEN'}, inplace=True)

In [15]:
# Display the first few rows to confirm the changes
print(df.head())

# Display the column names to ensure the changes were applied
print(df.columns)

      ID TYPE                                    PROGRAM       ORG PHONE  \
0  80015   FP                 THE BIBLE CHURCH OF CHRIST    718-293-1928
1  80026   FP         BRONX SEVENTH DAY ADVENTIST CHURCH    646-353-8926
2  80029   FP  BRONX TEMPLE SEVENTH DAY ADVENTIST CHURCH    718-842-4504
3  80065   FP                  GETHSEMANE BAPTIST CHURCH    347-948-0772
4  80081   FP                HOLY TABERNACLE CHURCH INC.  (718) 293-9862

       DAYS           HOURS  LONGITUDE   LATITUDE  \
0       SUN           4-6PM -73.968168  40.693683
1      THUR           2-5PM -73.955831  40.654492
2  M,W,THUR  11:30AM-2:30PM -73.912934  40.668113
3      THUR          8-10AM -73.963443  40.576623
4       TUE        4:30-5PM -73.912934  40.668113

                                        FULL ADDRESS   BOROUGH  ...   thur  \
0  138, Waverly Avenue, Clinton Hill, Brooklyn, K...  Brooklyn  ...  False
1  Bethanie Eglise Adventiste du 7eme Jour, 2059-...  Brooklyn  ...   True
2  521, Thomas S. Boyland Street, Brownsville, Br...  Brooklyn  ...   True
3  Ocean View Jewish Center, 3100, Brighton 4th S...  Brooklyn  ...   True
4  521, Thomas S. Boyland Street, Brownsville, Br...  Brooklyn  ...  False

     fri    sat    sun  WEEKS_OPEN  WEEK_1  WEEK_2  WEEK_3 WEEK_4  WEEK_5
0  False  False   True         2,4   False    True   False   True   False
1  False  False  False   1,2,3,4,5    True    True    True   True    True
2  False  False  False   1,2,3,4,5    True    True    True   True    True
3  False  False  False   1,2,3,4,5    True    True    True   True    True
4  False  False  False   1,2,3,4,5    True    True    True   True    True

[5 rows x 24 columns]
Index(['ID', 'TYPE', 'PROGRAM', 'ORG PHONE', 'DAYS', 'HOURS', 'LONGITUDE',
       'LATITUDE', 'FULL ADDRESS', 'BOROUGH', 'ZICODE', 'mon', 'tue', 'wed',
       'thur', 'fri', 'sat', 'sun', 'WEEKS_OPEN', 'WEEK_1', 'WEEK_2', 'WEEK_3',
       'WEEK_4', 'WEEK_5'],
      dtype='object')

In [16]:
check = df[['WEEKS_OPEN', 'WEEK_1', 'WEEK_2', 'WEEK_3', 'WEEK_4', 'WEEK_5']]

In [17]:
pd.set_option('display.max_rows', None)
check

    WEEKS_OPEN  WEEK_1  WEEK_2  WEEK_3  WEEK_4  WEEK_5
0          2,4   False    True   False    True   False
1    1,2,3,4,5    True    True    True    True    True
2    1,2,3,4,5    True    True    True    True    True
3    1,2,3,4,5    True    True    True    True    True
4    1,2,3,4,5    True    True    True    True    True
5    1,2,3,4,5    True    True    True    True    True
6    1,2,3,4,5    True    True    True    True    True
7    1,2,3,4,5    True    True    True    True    True
8    1,2,3,4,5    True    True    True    True    True
9    1,2,3,4,5    True    True    True    True    True
10   1,2,3,4,5    True    True    True    True    True
11   1,2,3,4,5    True    True    True    True    True
12   1,2,3,4,5    True    True    True    True    True
13   1,2,3,4,5    True    True    True    True    True
14   1,2,3,4,5    True    True    True    True    True
15   1,2,3,4,5    True    True    True    True    True
16   1,2,3,4,5    True    True    True    True    True
17   1,2,3,4,5    True    True    True    True    True
18       2,3,4   False    True    True    True   False
19   1,2,3,4,5    True    True    True    True    True
20   1,2,3,4,5    True    True    True    True    True
21           2   False    True   False   False   False
22   1,2,3,4,5    True    True    True    True    True
23   1,2,3,4,5    True    True    True    True    True
24   1,2,3,4,5    True    True    True    True    True
25   1,2,3,4,5    True    True    True    True    True
26         1,3    True   False    True   False   False
27   1,2,3,4,5    True    True    True    True    True
28   1,2,3,4,5    True    True    True    True    True
29   1,2,3,4,5    True    True    True    True    True
30   1,2,3,4,5    True    True    True    True    True
31   1,2,3,4,5    True    True    True    True    True
32   1,2,3,4,5    True    True    True    True    True
33   1,2,3,4,5    True    True    True    True    True
34   1,2,3,4,5    True    True    True    True    True
35   1,2,3,4,5    True    True    True    True    True
36   1,2,3,4,5    True    True    True    True    True
37   1,2,3,4,5    True    True    True    True    True
38   1,2,3,4,5    True    True    True    True    True
40   1,2,3,4,5    True    True    True    True    True
41   1,2,3,4,5    True    True    True    True    True
42   1,2,3,4,5    True    True    True    True    True
43     1,2,3,4    True    True    True    True   False
44   1,2,3,4,5    True    True    True    True    True
45   1,2,3,4,5    True    True    True    True    True
46   1,2,3,4,5    True    True    True    True    True
47   1,2,3,4,5    True    True    True    True    True
48   1,2,3,4,5    True    True    True    True    True
49   1,2,3,4,5    True    True    True    True    True
50         1,3    True   False    True   False   False
51         1,3    True   False    True   False   False
52   1,2,3,4,5    True    True    True    True    True
53         1,3    True   False    True   False   False
54   1,2,3,4,5    True    True    True    True    True
55   1,2,3,4,5    True    True    True    True    True
56       1,2,3    True    True    True   False   False
57   1,2,3,4,5    True    True    True    True    True
58   1,2,3,4,5    True    True    True    True    True
59         2,4   False    True   False    True   False
60   1,2,3,4,5    True    True    True    True    True
61         2,4   False    True   False    True   False
62   1,2,3,4,5    True    True    True    True    True
63   1,2,3,4,5    True    True    True    True    True
64   1,2,3,4,5    True    True    True    True    True
65   1,2,3,4,5    True    True    True    True    True
66   1,2,3,4,5    True    True    True    True    True
67   1,2,3,4,5    True    True    True    True    True
68   1,2,3,4,5    True    True    True    True    True
69   1,2,3,4,5    True    True    True    True    True
70   1,2,3,4,5    True    True    True    True    True
71   1,2,3,4,5    True    True    True    True    True
72   1,2,3,4,5    True    True    True    True    True
73         2,4   False    True   False    True   False
74     1,2,3,4    True    True    True    True   False
75   1,2,3,4,5    True    True    True    True    True
76   1,2,3,4,5    True    True    True    True    True
77   1,2,3,4,5    True    True    True    True    True
78   1,2,3,4,5    True    True    True    True    True
79   1,2,3,4,5    True    True    True    True    True
80   1,2,3,4,5    True    True    True    True    True
81   1,2,3,4,5    True    True    True    True    True
82   1,2,3,4,5    True    True    True    True    True
83   1,2,3,4,5    True    True    True    True    True
84   1,2,3,4,5    True    True    True    True    True
85   1,2,3,4,5    True    True    True    True    True
86   1,2,3,4,5    True    True    True    True    True
87   1,2,3,4,5    True    True    True    True    True
88   1,2,3,4,5    True    True    True    True    True
89   1,2,3,4,5    True    True    True    True    True
90   1,2,3,4,5    True    True    True    True    True
91   1,2,3,4,5    True    True    True    True    True
92   1,2,3,4,5    True    True    True    True    True
93   1,2,3,4,5    True    True    True    True    True
94   1,2,3,4,5    True    True    True    True    True
95   1,2,3,4,5    True    True    True    True    True
96   1,2,3,4,5    True    True    True    True    True
97   1,2,3,4,5    True    True    True    True    True
98   1,2,3,4,5    True    True    True    True    True
99   1,2,3,4,5    True    True    True    True    True
100  1,2,3,4,5    True    True    True    True    True
101  1,2,3,4,5    True    True    True    True    True
102  1,2,3,4,5    True    True    True    True    True
103  1,2,3,4,5    True    True    True    True    True
104  1,2,3,4,5    True    True    True    True    True
105  1,2,3,4,5    True    True    True    True    True
106  1,2,3,4,5    True    True    True    True    True
107  1,2,3,4,5    True    True    True    True    True
108  1,2,3,4,5    True    True    True    True    True
109  1,2,3,4,5    True    True    True    True    True
110  1,2,3,4,5    True    True    True    True    True
111  1,2,3,4,5    True    True    True    True    True
112  1,2,3,4,5    True    True    True    True    True
113  1,2,3,4,5    True    True    True    True    True
114  1,2,3,4,5    True    True    True    True    True
115  1,2,3,4,5    True    True    True    True    True
116    1,2,3,4    True    True    True    True   False
117  1,2,3,4,5    True    True    True    True    True
118  1,2,3,4,5    True    True    True    True    True
119  1,2,3,4,5    True    True    True    True    True
120  1,2,3,4,5    True    True    True    True    True
121  1,2,3,4,5    True    True    True    True    True
122  1,2,3,4,5    True    True    True    True    True
123  1,2,3,4,5    True    True    True    True    True
125  1,2,3,4,5    True    True    True    True    True
126  1,2,3,4,5    True    True    True    True    True
127  1,2,3,4,5    True    True    True    True    True
129  1,2,3,4,5    True    True    True    True    True
130  1,2,3,4,5    True    True    True    True    True
131  1,2,3,4,5    True    True    True    True    True
132  1,2,3,4,5    True    True    True    True    True
133  1,2,3,4,5    True    True    True    True    True
134    1,2,3,4    True    True    True    True   False
135  1,2,3,4,5    True    True    True    True    True
136  1,2,3,4,5    True    True    True    True    True
137  1,2,3,4,5    True    True    True    True    True
138  1,2,3,4,5    True    True    True    True    True
139  1,2,3,4,5    True    True    True    True    True
140  1,2,3,4,5    True    True    True    True    True
141  1,2,3,4,5    True    True    True    True    True
142  1,2,3,4,5    True    True    True    True    True
143  1,2,3,4,5    True    True    True    True    True
144  1,2,3,4,5    True    True    True    True    True
145  1,2,3,4,5    True    True    True    True    True
146  1,2,3,4,5    True    True    True    True    True
147  1,2,3,4,5    True    True    True    True    True
148  1,2,3,4,5    True    True    True    True    True
149  1,2,3,4,5    True    True    True    True    True
150  1,2,3,4,5    True    True    True    True    True
151  1,2,3,4,5    True    True    True    True    True
152  1,2,3,4,5    True    True    True    True    True
153  1,2,3,4,5    True    True    True    True    True
154  1,2,3,4,5    True    True    True    True    True
155  1,2,3,4,5    True    True    True    True    True
156  1,2,3,4,5    True    True    True    True    True
157  1,2,3,4,5    True    True    True    True    True
158  1,2,3,4,5    True    True    True    True    True
159  1,2,3,4,5    True    True    True    True    True
160  1,2,3,4,5    True    True    True    True    True
161    1,2,3,4    True    True    True    True   False
162          1    True   False   False   False   False
163  1,2,3,4,5    True    True    True    True    True
164  1,2,3,4,5    True    True    True    True    True
165  1,2,3,4,5    True    True    True    True    True
166  1,2,3,4,5    True    True    True    True    True
167  1,2,3,4,5    True    True    True    True    True
168  1,2,3,4,5    True    True    True    True    True
169        2,4   False    True   False    True   False
170        1,3    True   False    True   False   False
171  1,2,3,4,5    True    True    True    True    True
172  1,2,3,4,5    True    True    True    True    True
173  1,2,3,4,5    True    True    True    True    True
174  1,2,3,4,5    True    True    True    True    True
175  1,2,3,4,5    True    True    True    True    True
176  1,2,3,4,5    True    True    True    True    True
177  1,2,3,4,5    True    True    True    True    True
178  1,2,3,4,5    True    True    True    True    True
179  1,2,3,4,5    True    True    True    True    True
180  1,2,3,4,5    True    True    True    True    True
181  1,2,3,4,5    True    True    True    True    True
182  1,2,3,4,5    True    True    True    True    True
183  1,2,3,4,5    True    True    True    True    True
184  1,2,3,4,5    True    True    True    True    True
185  1,2,3,4,5    True    True    True    True    True
186  1,2,3,4,5    True    True    True    True    True
187  1,2,3,4,5    True    True    True    True    True
188  1,2,3,4,5    True    True    True    True    True
189  1,2,3,4,5    True    True    True    True    True
190  1,2,3,4,5    True    True    True    True    True
191  1,2,3,4,5    True    True    True    True    True
192  1,2,3,4,5    True    True    True    True    True
193  1,2,3,4,5    True    True    True    True    True
194  1,2,3,4,5    True    True    True    True    True
195  1,2,3,4,5    True    True    True    True    True
196  1,2,3,4,5    True    True    True    True    True
197  1,2,3,4,5    True    True    True    True    True
198        1,3    True   False    True   False   False
199  1,2,3,4,5    True    True    True    True    True
200  1,2,3,4,5    True    True    True    True    True
201  1,2,3,4,5    True    True    True    True    True
202  1,2,3,4,5    True    True    True    True    True
203  1,2,3,4,5    True    True    True    True    True
204  1,2,3,4,5    True    True    True    True    True
205  1,2,3,4,5    True    True    True    True    True
206  1,2,3,4,5    True    True    True    True    True
207  1,2,3,4,5    True    True    True    True    True
208  1,2,3,4,5    True    True    True    True    True
209  1,2,3,4,5    True    True    True    True    True
210  1,2,3,4,5    True    True    True    True    True
211  1,2,3,4,5    True    True    True    True    True
212  1,2,3,4,5    True    True    True    True    True
213  1,2,3,4,5    True    True    True    True    True
214  1,2,3,4,5    True    True    True    True    True
215  1,2,3,4,5    True    True    True    True    True
216  1,2,3,4,5    True    True    True    True    True
217  1,2,3,4,5    True    True    True    True    True
218  1,2,3,4,5    True    True    True    True    True
219  1,2,3,4,5    True    True    True    True    True
220  1,2,3,4,5    True    True    True    True    True
221  1,2,3,4,5    True    True    True    True    True
222  1,2,3,4,5    True    True    True    True    True
223        1,3    True   False    True   False   False
224  1,2,3,4,5    True    True    True    True    True
225  1,2,3,4,5    True    True    True    True    True
226  1,2,3,4,5    True    True    True    True    True
227  1,2,3,4,5    True    True    True    True    True
228  1,2,3,4,5    True    True    True    True    True
229  1,2,3,4,5    True    True    True    True    True
230  1,2,3,4,5    True    True    True    True    True
231  1,2,3,4,5    True    True    True    True    True
232  1,2,3,4,5    True    True    True    True    True
233  1,2,3,4,5    True    True    True    True    True
234  1,2,3,4,5    True    True    True    True    True
235  1,2,3,4,5    True    True    True    True    True
236  1,2,3,4,5    True    True    True    True    True
237  1,2,3,4,5    True    True    True    True    True
238  1,2,3,4,5    True    True    True    True    True
239          3   False   False    True   False   False
240        1,3    True   False    True   False   False
241  1,2,3,4,5    True    True    True    True    True
242  1,2,3,4,5    True    True    True    True    True
243  1,2,3,4,5    True    True    True    True    True
244  1,2,3,4,5    True    True    True    True    True
245  1,2,3,4,5    True    True    True    True    True
246  1,2,3,4,5    True    True    True    True    True
247  1,2,3,4,5    True    True    True    True    True
248  1,2,3,4,5    True    True    True    True    True
249  1,2,3,4,5    True    True    True    True    True
250  1,2,3,4,5    True    True    True    True    True
251  1,2,3,4,5    True    True    True    True    True
252  1,2,3,4,5    True    True    True    True    True
253  1,2,3,4,5    True    True    True    True    True
254  1,2,3,4,5    True    True    True    True    True
255  1,2,3,4,5    True    True    True    True    True
256  1,2,3,4,5    True    True    True    True    True
257  1,2,3,4,5    True    True    True    True    True
258  1,2,3,4,5    True    True    True    True    True
259  1,2,3,4,5    True    True    True    True    True
260  1,2,3,4,5    True    True    True    True    True
261  1,2,3,4,5    True    True    True    True    True
262  1,2,3,4,5    True    True    True    True    True
263  1,2,3,4,5    True    True    True    True    True
264  1,2,3,4,5    True    True    True    True    True
265        2,3   False    True    True   False   False
266  1,2,3,4,5    True    True    True    True    True
267  1,2,3,4,5    True    True    True    True    True
268  1,2,3,4,5    True    True    True    True    True
269        1,3    True   False    True   False   False
270  1,2,3,4,5    True    True    True    True    True
271  1,2,3,4,5    True    True    True    True    True
272        2,4   False    True   False    True   False
273  1,2,3,4,5    True    True    True    True    True
274  1,2,3,4,5    True    True    True    True    True
275  1,2,3,4,5    True    True    True    True    True
276  1,2,3,4,5    True    True    True    True    True
277    1,2,3,4    True    True    True    True   False
278  1,2,3,4,5    True    True    True    True    True
279  1,2,3,4,5    True    True    True    True    True
280  1,2,3,4,5    True    True    True    True    True
281  1,2,3,4,5    True    True    True    True    True
282    1,2,3,4    True    True    True    True   False
283  1,2,3,4,5    True    True    True    True    True
284  1,2,3,4,5    True    True    True    True    True
285  1,2,3,4,5    True    True    True    True    True
286  1,2,3,4,5    True    True    True    True    True
287  1,2,3,4,5    True    True    True    True    True
288  1,2,3,4,5    True    True    True    True    True
289        1,3    True   False    True   False   False
290        2,4   False    True   False    True   False
291  1,2,3,4,5    True    True    True    True    True
292  1,2,3,4,5    True    True    True    True    True
293  1,2,3,4,5    True    True    True    True    True
294  1,2,3,4,5    True    True    True    True    True
295  1,2,3,4,5    True    True    True    True    True
296  1,2,3,4,5    True    True    True    True    True
297  1,2,3,4,5    True    True    True    True    True
298  1,2,3,4,5    True    True    True    True    True
299  1,2,3,4,5    True    True    True    True    True
300  1,2,3,4,5    True    True    True    True    True
301  1,2,3,4,5    True    True    True    True    True
302  1,2,3,4,5    True    True    True    True    True
303  1,2,3,4,5    True    True    True    True    True
304  1,2,3,4,5    True    True    True    True    True
305  1,2,3,4,5    True    True    True    True    True
306  1,2,3,4,5    True    True    True    True    True
307  1,2,3,4,5    True    True    True    True    True
308  1,2,3,4,5    True    True    True    True    True
309          2   False    True   False   False   False
310  1,2,3,4,5    True    True    True    True    True
311  1,2,3,4,5    True    True    True    True    True
312  1,2,3,4,5    True    True    True    True    True
313          1    True   False   False   False   False
314  1,2,3,4,5    True    True    True    True    True
315  1,2,3,4,5    True    True    True    True    True
316  1,2,3,4,5    True    True    True    True    True
317  1,2,3,4,5    True    True    True    True    True
318  1,2,3,4,5    True    True    True    True    True
319    1,2,3,4    True    True    True    True   False
320  1,2,3,4,5    True    True    True    True    True
321  1,2,3,4,5    True    True    True    True    True
322  1,2,3,4,5    True    True    True    True    True
323  1,2,3,4,5    True    True    True    True    True
324  1,2,3,4,5    True    True    True    True    True
325  1,2,3,4,5    True    True    True    True    True
326  1,2,3,4,5    True    True    True    True    True
327  1,2,3,4,5    True    True    True    True    True
328  1,2,3,4,5    True    True    True    True    True
329  1,2,3,4,5    True    True    True    True    True
330  1,2,3,4,5    True    True    True    True    True
331  1,2,3,4,5    True    True    True    True    True
332  1,2,3,4,5    True    True    True    True    True
333  1,2,3,4,5    True    True    True    True    True
334  1,2,3,4,5    True    True    True    True    True
335  1,2,3,4,5    True    True    True    True    True
336    1,2,3,4    True    True    True    True   False
337  1,2,3,4,5    True    True    True    True    True
338  1,2,3,4,5    True    True    True    True    True
339    1,2,3,4    True    True    True    True   False
340  1,2,3,4,5    True    True    True    True    True
341  1,2,3,4,5    True    True    True    True    True
342  1,2,3,4,5    True    True    True    True    True
343          4   False   False   False    True   False
344  1,2,3,4,5    True    True    True    True    True
345  1,2,3,4,5    True    True    True    True    True
346  1,2,3,4,5    True    True    True    True    True
347  1,2,3,4,5    True    True    True    True    True
348  1,2,3,4,5    True    True    True    True    True
349  1,2,3,4,5    True    True    True    True    True
350  1,2,3,4,5    True    True    True    True    True
351        1,3    True   False    True   False   False
352  1,2,3,4,5    True    True    True    True    True
353  1,2,3,4,5    True    True    True    True    True
354  1,2,3,4,5    True    True    True    True    True
355  1,2,3,4,5    True    True    True    True    True
356        1,3    True   False    True   False   False
357  1,2,3,4,5    True    True    True    True    True
358  1,2,3,4,5    True    True    True    True    True
359        2,4   False    True   False    True   False
360  1,2,3,4,5    True    True    True    True    True
361          2   False    True   False   False   False
362        2,4   False    True   False    True   False
363          4   False   False   False    True   False
364  1,2,3,4,5    True    True    True    True    True

In [18]:
# Select the relevant columns for the database
df_to_insert = df[['ID', 'WEEKS_OPEN', 'WEEK_1', 'WEEK_2', 'WEEK_3', 'WEEK_4', 'WEEK_5']]

In [19]:
import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Retrieve the environment variables
url: str = os.getenv("SUPABASE_URL")
key: str = os.getenv("SUPABASE_KEY")

# Initialize Supabase client
supabase: Client = create_client(url, key)

In [22]:
# Rename the columns to lowercase
df.rename(columns={
    'WEEKS_OPEN': 'weeks_open',
    'WEEK_1': 'week_1',
    'WEEK_2': 'week_2',
    'WEEK_3': 'week_3',
    'WEEK_4': 'week_4',
    'WEEK_5': 'week_5'
}, inplace=True)

In [27]:
df_to_insert = df[['ID', 'weeks_open', 'week_1', 'week_2', 'week_3', 'week_4', 'week_5']]
data_list = df_to_insert.to_dict(orient='records')

# Step 3: Upsert the data
response = supabase.table('food').upsert(data_list).execute()

# Step 4: Verify the data
verify_response = supabase.table('food').select('ID', 'weeks_open', 'week_1', 'week_2', 'week_3', 'week_4', 'week_5').limit(5).execute()

print(verify_response.data)

[{'ID': 80345, 'weeks_open': '1,2,3,4,5', 'week_1': True, 'week_2': True, 'week_3': True, 'week_4': True, 'week_5': True}, {'ID': 81595, 'weeks_open': '1,2,3,4,5', 'week_1': True, 'week_2': True, 'week_3': True, 'week_4': True, 'week_5': True}, {'ID': 82033, 'weeks_open': '1,2,3,4,5', 'week_1': True, 'week_2': True, 'week_3': True, 'week_4': True, 'week_5': True}, {'ID': 83082, 'weeks_open': '1,2,3,4,5', 'week_1': True, 'week_2': True, 'week_3': True, 'week_4': True, 'week_5': True}, {'ID': 83311, 'weeks_open': '1,2,3,4,5', 'week_1': True, 'week_2': True, 'week_3': True, 'week_4': True, 'week_5': True}]